### ISSUE TITLE
Introduce versioning for janus, janus plugins

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1006] opened 2015-11-24 17:59 UTC
Continuation of #951 

Make sure correct versioning is used, e.g. https://github.com/cargomedia/puppet-packages/pull/951/files#diff-185b5f15d1ada2040a101f460cf852e1R9 does not

Use the new [`git::repository` resource](https://github.com/cargomedia/puppet-packages/pull/1003)

**Comment by njam** [comment] 2015-11-25 08:32
Duplicate of https://github.com/cargomedia/puppet-packages/issues/999 ?

**Closed** 2015-11-25 10:42 UTC
