### ISSUE TITLE
Build fails (for Jenkins)

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#909] opened 2015-07-05 19:57 UTC
```
Finished in 156 minutes 22 seconds (files took 0.46703 seconds to load)
635 examples, 23 failures

Failed examples:

rspec ./modules/nfs/spec/default/spec.rb:6 # nfs File "/tmp/source/foo"
rspec ./modules/nfs/spec/default/spec.rb:10 # nfs Service "nfs-common"
rspec ./modules/nfs/spec/default/spec.rb:11 # nfs Service "nfs-common"
rspec ./modules/nfs/spec/default/spec.rb:15 # nfs Service "nfs-kernel-server"
rspec ./modules/nfs/spec/default/spec.rb:16 # nfs Service "nfs-kernel-server"
rspec ./modules/nfs/spec/default/spec.rb:20 # nfs Command "monit summary | grep nfs-server" exit_status
rspec ./modules/nfs/spec/default/spec.rb:24 # nfs Command "ps ax | grep "\[nfsd\]" | wc -l" exit_status
rspec ./modules/nfs/spec/default/spec.rb:25 # nfs Command "ps ax | grep "\[nfsd\]" | wc -l" stdout
rspec ./modules/nfs/spec/default/spec.rb:29 # nfs File "/tmp/source/bar"
rspec ./modules/nfs/spec/default/spec.rb:33 # nfs File "/nfsexport/shared/foo"
rspec ./modules/nfs/spec/default/spec.rb:37 # nfs File "/nfsexport/shared/bar"
rspec ./modules/nfs/spec/default/spec.rb:41 # nfs File "/tmp/mounted"
rspec ./modules/nfs/spec/default/spec.rb:42 # nfs File "/tmp/mounted"
rspec ./modules/nfs/spec/default/spec.rb:43 # nfs File "/tmp/mounted"
rspec ./modules/nfs/spec/default/spec.rb:44 # nfs File "/tmp/mounted"
rspec ./modules/nfs/spec/default/spec.rb:45 # nfs File "/tmp/mounted"
rspec ./modules/nfs/spec/default/spec.rb:49 # nfs File "/tmp/mounted/bar"
rspec ./modules/nfs/spec/default/spec.rb:53 # nfs File "/nfsexport/shared"
rspec ./modules/nfs/spec/default/spec.rb:54 # nfs File "/nfsexport/shared"
rspec ./modules/nfs/spec/default/spec.rb:55 # nfs File "/nfsexport/shared"
rspec ./modules/nfs/spec/default/spec.rb:56 # nfs File "/nfsexport/shared"
rspec ./modules/phpmyadmin/spec/init/spec.rb:6 # phpmyadmin Package "phpmyadmin"
rspec ./modules/phpmyadmin/spec/init/spec.rb:10 # phpmyadmin Command "curl -L http://localhost/phpmyadmin" stdout
```

**Comment by njam** [comment] 2015-07-06 15:38
Error:
```
       Command failed: 
       [mNotice: Compiled catalog for debian-7-amd64-default.vagrantup.com in environment production in 0.69 seconds[0m
       [mNotice: /Stage[main]/Main/Node[default]/Exec[wait_5_sec_for_nfs_export_to_become_ready]/returns: executed successfully[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Exec[prepare /tmp/mounted]/returns: executed successfully[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Mount[/tmp/mounted]/ensure: defined 'ensure' as 'defined'[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Mount[/tmp/mounted]: Triggered 'refresh' from 1 events[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Cron[mount-check /tmp/mounted]/ensure: created[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Exec[/usr/sbin/mount-check.sh /tmp/mounted]/returns: Mountpoint not mounted: /tmp/mounted - remounting...[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Exec[/usr/sbin/mount-check.sh /tmp/mounted]/returns: mount.nfs4: access denied by server while mounting localhost:/shared[0m
       [mNotice: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Exec[/usr/sbin/mount-check.sh /tmp/mounted]/returns: Failed to remount![0m
       [1;31mError: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Exec[/usr/sbin/mount-check.sh /tmp/mounted]: Failed to call refresh: /usr/sbin/mount-check.sh /tmp/mounted returned 1 instead of one of [0][0m
       [1;31mError: /Stage[main]/Main/Node[default]/Nfs::Mount[/tmp/mounted]/Mount::Entry[/tmp/mounted]/Exec[/usr/sbin/mount-check.sh /tmp/mounted]: /usr/sbin/mount-check.sh /tmp/mounted returned 1 instead of one of [0][0m
       [mNotice: /Stage[main]/Main/Node[default]/File[/tmp/mounted/bar]/ensure: created[0m
       [mNotice: Finished catalog run in 8.32 seconds[0m
```

Can't reproduce locally yet.

**Comment by njam** [comment] 2015-07-06 15:45
Happens since the build of 2015-07-02. No changes in code since then.

Tests succeed also on ci2 when running *only* NFS tests...

Hmhmhm. How about dropping the NFS module? :)

**Comment by kris-lab** [comment] 2015-07-08 07:05
agree, why not. it is kind of outdated technology. I don't think so we would step back:) ?

**Comment by njam** [comment] 2015-07-08 08:07
Hm I think it's actually just flaky - the test succeeded today (but "autoprefixer" failed randomly).
Let's wait another day, but probably retrying tests would solve this: https://github.com/cargomedia/puppet-packages/issues/885

**Comment by njam** [comment] 2015-07-13 09:23
fixed by https://github.com/cargomedia/puppet-packages/pull/910

**Closed by njam** 2015-07-13 09:23 UTC
Labels: bug
