### ISSUE TITLE
Install ffmpeg from deb package

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1208] opened 2016-03-14 10:27 UTC
When migrating please delete the old binaries (`/usr/local/bin/ff*`?).

Via https://github.com/cargomedia/debian-packages/pull/99

**Comment by ppp0** [comment] 2016-03-14 15:29
duplicate of https://github.com/cargomedia/puppet-packages/pull/1143

**Closed by ppp0** 2016-03-14 15:29 UTC
Labels: ready
